### ISSUE TITLE
Werde von VsCode auf Mac Homebildschirm geschmissen beim Ausführen von MIPS code via "Shift + Command + P"

### ISSUE THREAD

**Issue by NiclasKober** [akainth015/marscode#1]
Issue Type: <b>Bug</b>

Guten Tag,
wenn ich mein MIPS Assembler Programm via "Shift + Command + P" und dann "MARS: Assemble and run" ausführen will( Screenshot 1), werde ich von VsCode zu meinem Mac Home Bildschrim geschmissen und Java öffnet sich (siehe Screenshot 2). Was hat es damit auf sich?

Mein MIPS Programm zum testen:

#
# data declaration
#

.data
const5: .float 5.0
const9: .float 9.0
const32: .float 32.0
const273: .float -273.15  #absoluter Nullpunkt (neu)

#input: .float -459.67

#
# code
#

.globl main
.text

main:
    ### load input and call function
    
    li $v0, 6 #read_float (neu)
    syscall 
    mov.s $f12, $f0 # $f12, da: siehe MIPS Blatt
    jal f2c #springe zu f2c

    ###print output

    mov.s $f12, $f0 #move output of f2c into $f12 input register
    li $v0, 2  # load immidiate as code for print_float
    syscall
    li $v0, 10 #Exit(neu)
    syscall

f2c:
    lwc1 $f18, const5 #laden & speichern von Gleitkommazahl
    lwc1 $f20, const9 #   "
    div.s $f22, $f18, $f20 # $f24 = 5/9
    lwc1 $f24, const32
    sub.s $f0, $f12, $f24  # $f0 = fahr - 32
    mul.s $f0, $f22, $f0 # $F0 = 5/9 * (fahr -32)
    lwc1 $f3, const273 #laden und speichern von -273.15 in $f3 (neu)
    c.le.s $f0, $f3 #vergleicht $f0 und $f3 (ob niedriger als Nullpunkt)
    bc1t nullpunkt #wenn $f0 größer(negativer) ist als $f3 ist springe zu nullpunkt (branch if c equals 1)
    jr $ra  #zurück zu main
    nullpunkt:
    mov.s $f0, $f3 #setze -273.15
    jr $ra #zurück zu main

Extension version: 1.2.2
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:04.972Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv|--crash-reporter-id c27e9c26-57eb-4c2c-b8a1-23156098d615|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

<!-- generated by issue reporter --
<img width="632" alt="Bildschirmfoto 2022-07-01 um 17 31 53" src="https://user-images.githubusercontent.com/95416029/176925431-9d88704d-7d04-48a2-a4e3-5ecb13fb2869
<img width="511" alt="Bildschirmfoto 2022-07-01 um 17 34 23" src="https://user-images.githubusercontent.com/95416029/176925592-5acd1857-23b7-4bed-a120-cb5947f251b3.png">
.png">

**Comment by akainth015** [comment]
Thank you for reporting the issue. Can you please attach the screenshots that you referred to, and also the JRE version?

```sh
java -version
```

**Comment by NiclasKober** [comment]
<img width="610" alt="Bildschirmfoto 2022-07-02 um 10 39 30" src="https://user-images.githubusercontent.com/95416029/176993767-c1012414-0422-4586-a6c3-21b1b3fba36a.png">


![Bildschirmfoto 2022-07-02 um 10 40 31](https://user-images.githubusercontent.com/95416029/176993774-c62db736-64cb-4c23-b087-e2b65f2e57e4.jpeg)


java -18.0.1.1  (Oracle open JDK, aarch 64)

**Comment by NiclasKober** [comment]
Wichtig zu erwähnen wäre noch das VSCode im Vollbildmodus ist und dann der Code ausgeführt wird.

**Comment by akainth015** [comment]
> ```sh
> java -18.0.1.1 (Oracle open JDK, aarch 64)
> ```

Unfortunately, the MARS IDE relies on Java 8, so having Java 18 on your `PATH` will cause issues with the extension. 

[This line of code](https://github.com/akainth015/marscode/blob/main/src/extension.ts#L65) is the one that causes `PATH` to be used to find `java`. If you require Java 18 to be on the path, you could trivially implement a new setting for the `java` executable that is used.
